// English blocklist. Same conventions as Spanish: lowercase, no diacritics,
// substring matching. Short words (< 4 chars) go into `englishExactOnly`.
export const englishProfanity = [
  // Sexual / vulgar
  'fuck', 'fucker', 'fucked', 'fucking', 'fucks', 'motherfucker', 'mofo',
  'shit', 'shitty', 'shithead', 'shitface', 'bullshit', 'shitting',
  'bitch', 'bitches', 'biatch', 'btch',
  'asshole', 'arsehole', 'asshat', 'asswipe', 'jackass', 'dumbass',
  'bastard', 'bastards',
  'damn', 'goddamn', 'goddammit', 'damnit',
  'piss', 'pissed', 'pisser',
  'cunt', 'cunts',
  'pussy', 'pussies',
  'cock', 'cocks', 'cocksucker', 'cocksucking',
  'dick', 'dickhead', 'dickface', 'dicks',
  'prick', 'pricks',
  'twat', 'twats',
  'wank', 'wanker', 'wanking',
  'jerk', 'jerkoff', 'jerkface',
  'whore', 'whores', 'slut', 'sluts', 'slutty',
  'hooker', 'hookers',
  'tits', 'titties', 'titty', 'boobies',
  'blowjob', 'blowjobs', 'handjob', 'handjobs', 'rimjob',
  'orgasm', 'orgasms', 'cum', 'cumming', 'jizz',
  'rape', 'raped', 'rapist', 'rapists',
  'pedophile', 'paedophile', 'pedo',

  // Slurs / hate (zero tolerance)
  'nigger', 'niggers', 'nigga', 'niggas', 'nigguh', 'nigguz', 'niggah',
  'faggot', 'faggots', 'fag',
  'dyke', 'dykes',
  'tranny', 'trannies',
  'kike', 'kikes',
  'spic', 'spics', 'wetback', 'wetbacks',
  'chink', 'chinks', 'gook', 'gooks',
  'paki', 'pakis',
  'retard', 'retarded', 'retards',
  'mongoloid',
  'gypsy scum', 'gypped',
  'nazi', 'nazis', 'heil hitler', 'sieg heil', 'kkk',
  'white power', 'jewry', 'jewish dog',
  'islamist scum',

  // Vulgar phrases
  'go fuck yourself', 'fuck off', 'fuck you', 'screw you',
  'eat shit', 'kiss my ass', 'kissmyass',
  'son of a bitch', 'sonofabitch', 'sob bitch',
  'piece of shit', 'pieceofshit',

  // Threats / violence
  'kill yourself', 'kys', 'kill myself', 'i will kill',
  'shoot you', 'stab you', 'hang you',
  'bomb the', 'school shooter', 'mass shooter',

  // Drugs
  'crack whore', 'meth head', 'crackhead',
];

// ─── English joke / gag names ────────────────────────────────────────────────
// Same format as Spanish: [concat_form, why]. Curated from ~380 candidates
// returned by the research agent. Removed entries that conflict with real
// celebrity names (Don Quihote, Holden = Holden Caulfield etc.) and weak puns
// where the connection produces a real common word.
export const englishJokeNames = [
  // ── Mike Hunt / Mike Hawk (my cunt / my cock)
  ['mikehunt', 'Mike Hunt → "my cunt"'],
  ['mikehunthertz', 'Mike Hunt Hertz → "my cunt hurts"'],
  ['mikehuntitches', 'Mike Hunt Itches → "my cunt itches"'],
  ['mikehawk', 'Mike Hawk → "my cock"'],
  ['mikehawkbigg', 'Mike Hawk Bigg → "my cock\'s big"'],
  ['mikehawkhertz', 'Mike Hawk Hertz → "my cock hurts"'],
  ['mikehawksmells', 'Mike Hawk Smells → "my cock smells"'],
  ['mikerotch', 'Mike Rotch → "my crotch"'],
  ['mikelitoris', 'Mike Litoris → "my clitoris"'],

  // ── Mike Ox- (my cock's …)
  ['mikeoxlong', 'Mike Oxlong → "my cock\'s long"'],
  ['mikeoxbig', 'Mike Oxbig → "my cock\'s big"'],
  ['mikeoxsmall', 'Mike Oxsmall → "my cock\'s small"'],
  ['mikeoxhurt', 'Mike Oxhurt → "my cock hurt"'],
  ['mikeoxhard', 'Mike Oxhard → "my cock\'s hard"'],
  ['mikeoxlimp', 'Mike Oxlimp → "my cock\'s limp"'],
  ['mikeoxout', 'Mike Oxout → "my cock\'s out"'],
  ['mikeoxsore', 'Mike Oxsore → "my cock\'s sore"'],
  ['mikeoxwet', 'Mike Oxwet → "my cock\'s wet"'],
  ['mikeoxhugh', 'Mike Oxhugh → "my cock\'s huge"'],
  ['mikecoxafloppin', 'Mike Coxafloppin → "my cock\'s a-flopping"'],
  ['mikecoxapleezure', 'Mike Coxapleezure → "my cock\'s a pleasure"'],

  // ── Hugh G./Hugh J. (huge …)
  ['hughjass', 'Hugh Jass → "huge ass"'],
  ['hughgrection', 'Hugh G. Rection → "huge erection"'],
  ['hughjanus', 'Hugh Janus → "huge anus"'],
  ['hughgpenis', 'Hugh G. Penis → "huge penis"'],
  ['hughjardon', 'Hugh Jardon → "huge hard-on"'],
  ['hughjorgan', 'Hugh Jorgan → "huge organ"'],
  ['hughmungus', 'Hugh Mungus → "humongous"'],
  ['hughmongous', 'Hugh Mongous → "humongous"'],
  ['hughjcock', 'Hugh J. Cock → "huge cock"'],
  ['hughjdick', 'Hugh J. Dick → "huge dick"'],
  ['hughjkahonas', 'Hugh J. Kahonas → "huge cojones"'],
  ['hughjboobs', 'Hugh J. Boobs → "huge boobs"'],
  ['hughjknockers', 'Hugh J. Knockers → "huge knockers"'],
  ['hughjrack', 'Hugh J. Rack → "huge rack"'],
  ['hughjbalz', 'Hugh J. Balz → "huge balls"'],
  ['hughjbutt', 'Hugh J. Butt → "huge butt"'],
  ['hughjbumm', 'Hugh J. Bumm → "huge bum"'],
  ['hughdick', 'Hugh Dick → "huge dick"'],
  ['hughboobies', 'Hugh Boobies → "huge boobies"'],
  ['hughtits', 'Hugh Tits → "huge tits"'],
  ['hughschlong', 'Hugh Schlong → "huge schlong"'],
  ['hughwahn', 'Hugh Wahn → "huge one"'],
  ['hughgeraction', 'Hugh Geraction → "huge erection"'],
  ['hughracocke', 'Hugh R. A-Cocke → "you are a cock"'],
  ['hughraprick', 'Hugh R. A-Prick → "you are a prick"'],
  ['hughranasshole', 'Hugh R. An Asshole → "you are an asshole"'],
  ['hughrawanker', 'Hugh R. A-Wanker → "you are a wanker"'],
  ['hughratwat', 'Hugh R. A-Twat → "you are a twat"'],
  ['hughraknob', 'Hugh R. A-Knob → "you are a knob"'],
  ['hughrhung', 'Hugh R. Hung → "you are hung"'],

  // ── Ben Dover / Eileen Dover (bend over)
  ['bendover', 'Ben Dover → "bend over"'],
  ['eileendover', 'Eileen Dover → "I lean over"'],
  ['ilenedover', 'Ilene Dover → "I lean over"'],
  ['rhodadover', 'Rhoda Dover → "rode her over"'],

  // ── Seymour … (see more …)
  ['seymourbutts', 'Seymour Butts → "see more butts"'],
  ['seymourheinie', 'Seymour Heinie → "see more heinie"'],
  ['seymourcox', 'Seymour Cox → "see more cocks"'],
  ['seymourbeaver', 'Seymour Beaver → "see more beaver"'],
  ['seymourasscher', 'Seymour Asscher → "see more ass"'],
  ['seymourkunst', 'Seymour Kunst → "see more cunts"'],

  // ── Amanda … (a man to …)
  ['amandahugginkiss', 'Amanda Hugginkiss → "a man to hug and kiss"'],
  ['amandahuginkiss', 'Amanda Huginkiss → "a man to hug and kiss"'],
  ['amandamount', 'Amanda Mount → "a man to mount"'],
  ['amandapoker', 'Amanda Poker → "a man to poke her"'],
  ['amandalickaboy', 'Amanda Lickaboy (vulgar)'],

  // ── Bart Simpson canon (Moe's Tavern prank calls)
  ['beaoproblem', 'Bea O\'Problem → "B.O. problem"'],
  ['ivanatinkle', 'Ivana Tinkle → "I wanna tinkle"'],
  ['ivanahumpalot', 'Ivana Humpalot → "I wanna hump a lot"'],
  ['ivanamandic', 'Ivana Mandic → "I wanna man dick"'],
  ['ivanapintsivit', 'Ivana Pintsivit → "I wanna pint of it"'],
  ['oliverclothesoff', 'Oliver Clothesoff → "all of her clothes off"'],
  ['heywoodjablome', 'Heywood Jablome → "hey, would you blow me"'],
  ['heywoodyablowme', 'Heywood Yablowme → "hey, would you blow me"'],
  ['heywoodjadome', 'Heywood Jadome → "hey, would you do me"'],
  ['heywoodjaeatme', 'Heywood Jaeatme → "hey, would you eat me"'],
  ['heywoodubuggerme', 'Heywood U. Buggerme → "hey, would you bugger me"'],

  // ── Al Coholic / Al-
  ['alcoholic', 'Al Coholic → "alcoholic"'],
  ['alcohall', 'Al Cohall → "alcohol"'],

  // ── I.P. / I.C. / I.M.A.
  ['ipfreely', 'I.P. Freely → "I pee freely"'],
  ['ipdaly', 'I.P. Daly → "I pee daily"'],
  ['ipknightly', 'I.P. Knightly → "I pee nightly"'],
  ['icweiner', 'I.C. Weiner → "I see wiener"'],
  ['imhung', 'I.M. Hung → "I\'m hung"'],
  ['imaputz', 'I.M.A. Putz → "I\'m a putz"'],
  ['imahoare', 'I.M.A. Hoare → "I\'m a whore"'],
  ['imaboozer', 'I.M.A. Boozer → "I\'m a boozer"'],
  ['imaloozer', 'I.M.A. Loozer → "I\'m a loser"'],
  ['imahooker', 'I.M.A. Hooker → "I\'m a hooker"'],
  ['imapussy', 'Ima Pussy → "I\'m a pussy"'],
  ['imadick', 'Ima Dick → "I\'m a dick"'],
  ['imawhore', 'Ima Whore → "I\'m a whore"'],
  ['imaslutt', 'Ima Slutt → "I\'m a slut"'],
  ['imawiener', 'Ima Wiener → "I\'m a wiener"'],

  // ── Phil … (fill my …)
  ['philmccavity', 'Phil McCavity → "fill my cavity"'],
  ['philipmccavity', 'Philip McCavity → "fill up my cavity"'],
  ['philmccracken', 'Phil McCracken → "fill my crack in"'],
  ['philmahole', 'Phil Mahole → "fill my hole"'],
  ['philmahooha', 'Phil Mahooha → "fill my hoo-ha"'],
  ['philmybutt', 'Phil My Butt → "fill my butt"'],
  ['philmcgroin', 'Phil McGroin → "fill my groin"'],
  ['phillatio', 'Phil Latio → "fellatio"'],
  ['phillecio', 'Phil Lecio → "fellatio"'],
  ['philerupp', 'Phil Erupp → "fill her up"'],
  ['philmybung', 'Phil Mybung → "fill my bung (anus)"'],
  ['philmybox', 'Phil Mybox → "fill my box"'],
  ['philrcrack', 'Phil R. Crack → "fill her crack"'],
  ['philyarball', 'Phil Yarball → "fill your balls"'],
  ['philahole', 'Phil A. Hole → "fill a hole"'],

  // ── Pat … (pat my …)
  ['patmycrotch', 'Pat Mycrotch → "pat my crotch"'],
  ['patmybutt', 'Pat Mybutt → "pat my butt"'],
  ['patmahole', 'Pat Mahole → "pat my hole"'],
  ['patmagroin', 'Pat Magroin → "pat my groin"'],
  ['patmagina', 'Pat Magina → "pat (my) vagina"'],
  ['patmcgroin', 'Pat McGroin → "pat my groin"'],
  ['patmywiener', 'Pat My Wiener → "pat my wiener"'],
  ['pathispenis', 'Pat His Penis → "pat his penis"'],
  ['patmybox', 'Pat My Box → "pat my box"'],
  ['patmagenitals', 'Pat Magenitals → "pat my genitals"'],

  // ── Anita … (I need a …)
  ['anitamann', 'Anita Mann → "I need a man"'],
  ['anitadick', 'Anita Dick → "I need a dick"'],
  ['anitabath', 'Anita Bath → "I need a bath"'],
  ['anitalay', 'Anita Lay → "I need a lay"'],
  ['anitahummer', 'Anita Hummer → "I need a hummer"'],
  ['anitabigwun', 'Anita Bigwun → "I need a big one"'],
  ['anitabeaver', 'Anita Beaver → "I need a beaver"'],
  ['anitagoodfuk', 'Anita Goodfuk → "I need a good fuck"'],
  ['anitagoodlay', 'Anita Goodlay → "I need a good lay"'],
  ['anitastiffwun', 'Anita Stiffwun → "I need a stiff one"'],
  ['anitapee', 'Anita Pee → "I need to pee"'],
  ['anitapoo', 'Anita Poo → "I need a poo"'],
  ['anitadoosh', 'Anita Doosh → "I need a douche"'],
  ['anitahardman', 'Anita Hardman → "I need a hard man"'],
  ['anitabigblackone', 'Anita Bigblackone → "I need a big black one"'],

  // ── Connie / Jenny / Norma (genital euphemisms)
  ['connielingus', 'Connie Lingus → "cunnilingus"'],
  ['connielingys', 'Connie Lingys → "cunnilingus"'],
  ['connieliver', 'Connie Liver → "cunnilinger"'],
  ['dixienormous', 'Dixie Normous → "dick\'s enormous"'],
  ['dixiewrecked', 'Dixie Wrecked → "dick\'s wrecked"'],
  ['jennytals', 'Jenny Tals → "genitals"'],
  ['jennytaylia', 'Jenny Taylia → "genitalia"'],
  ['jennatilia', 'Jenna Tilia → "genitalia"'],
  ['jennytalia', 'Jenny Talia → "genitalia"'],
  ['jennytailia', 'Jenny Tailia → "genitalia"'],
  ['normastitz', 'Norma Stitz → "enormous tits"'],
  ['normasnockers', 'Norma Snockers → "enormous knockers"'],

  // ── Harry … (hairy …)
  ['harrybaals', 'Harry Baals → "hairy balls"'],
  ['harrysachs', 'Harry Sachs → "hairy sacks"'],
  ['harrypness', 'Harry P. Ness → "hairy penis"'],
  ['harrybeaver', 'Harry Beaver → "hairy beaver"'],
  ['harrypitts', 'Harry Pitts → "hairy pits"'],
  ['harrycox', 'Harry Cox → "hairy cocks"'],
  ['harrybuns', 'Harry Buns → "hairy buns"'],
  ['harrykrotch', 'Harry Krotch → "hairy crotch"'],
  ['harrytweat', 'Harry Tweat → "hairy twat"'],
  ['harryazcrack', 'Harry Azcrack → "hairy ass crack"'],
  ['harrywang', 'Harry Wang → "hairy wang"'],
  ['hairydick', 'Hairy Dick → "hairy dick"'],

  // ── Maya / Wilma (my … / will my …)
  ['mayabuttreeks', 'Maya Buttreeks → "my butt reeks"'],
  ['mayanormusbutt', 'Maya Normusbutt → "my enormous butt"'],
  ['mayadixafat', 'Maya Dixafat → "my dick\'s a fat one"'],
  ['wilmadiqfit', 'Wilma Diqfit → "will my dick fit"'],
  ['wilmafingerfit', 'Wilma Finger Fit → "will my finger fit"'],
  ['wilmabuttreeks', 'Wilma Buttreeks → "will my butt reek"'],
  ['wilmahoohafit', 'Wilma Hooha Fit → "will my hoo-ha fit"'],

  // ── Rusty / Craven / Holden / Dixie / Mister (sexual)
  ['rustykuntz', 'Rusty Kuntz → "rusty cunts"'],
  ['cravenmoorehead', 'Craven Moorehead → "craving more head"'],
  ['cravinmoorehead', 'Cravin Moorehead → "craving more head"'],
  ['kravenmoorehead', 'Kraven Moorehead → "craving more head"'],
  ['holdenmywang', 'Holden Mywang → "holding my wang"'],
  ['holdenmygroin', 'Holden Mygroin → "holding my groin"'],
  ['holdenmycock', 'Holden Mycock → "holding my cock"'],
  ['holdenmydick', 'Holden Mydick → "holding my dick"'],
  ['holdenmynutts', 'Holden Mynutts → "holding my nuts"'],
  ['holdenmcgroin', 'Holden McGroin → "holding my groin"'],
  ['holdenonnemynuts', 'Holden On To My Nuts'],
  ['donkeedick', 'Don Keedick → "donkey dick"'],
  ['drewpeacock', 'Drew Peacock → "droopy cock"'],
  ['drewpeakock', 'Drew Peakock → "droopy cock"'],
  ['mrklitz', 'Mr. Klitz → "Mr. Clits"'],
  ['masterbates', 'Master Bates → "masturbates"'],
  ['masterbate', 'Master Bate → "masturbate"'],

  // ── Justin … (just in …)
  ['justinsider', 'Justin Sider → "just inside her"'],
  ['justinhale', 'Justin Hale → "just inhale"'],
  ['justintrouble', 'Justin Trouble → "just in trouble"'],

  // ── Wayne Kerr (wanker)
  ['waynekerr', 'Wayne Kerr → "wanker"'],

  // ── Jacques / Jack (jock strap, jack off)
  ['jacquesstrap', 'Jacques Strap → "jock strap"'],
  ['jacqueshoff', 'Jacques Hoff → "jack off"'],
  ['jackgoff', 'Jack Goff → "jack off"'],
  ['jackmehoff', 'Jack Mehoff → "jack me off"'],
  ['jackmehoffer', 'Jack Mehoffer → "jack me off"'],
  ['jackmeioff', 'Jack Meioff → "jack me off"'],
  ['jackmeeoff', 'Jack Meeoff → "jack me off"'],
  ['jackknoff', 'Jack Knoff → "jack off"'],
  ['jackhoff', 'Jack Hoff → "jack off"'],
  ['jacktortoff', 'Jack Tortoff → "jacked off"'],

  // ── Drug / sex jokes
  ['marychristmas', 'Mary Christmas → "Merry Christmas (gag)"'],
  ['maryjuana', 'Mary Juana → "marijuana"'],
  ['krystalmeth', 'Krystal Meth → "crystal meth"'],
  ['bustercherry', 'Buster Cherry → "bust her cherry"'],
  ['busterhyman', 'Buster Hyman → "bust her hymen"'],
  ['busternutt', 'Buster Nutt → "bust a nut"'],
  ['bustinanutt', 'Bustin A Nutt → "busting a nut"'],

  // ── Eura … (you\'re a …)
  ['eurapussy', 'Eura Pussy → "you\'re a pussy"'],
  ['euradick', 'Eura Dick → "you\'re a dick"'],
  ['eurafagit', 'Eura Fagit → "you\'re a faggot"'],
  ['eurabitch', 'Eura Bitch → "you\'re a bitch"'],
  ['euraslutt', 'Eura Slutt → "you\'re a slut"'],
  ['eurahooker', 'Eura Hooker → "you\'re a hooker"'],
  ['euraputz', 'Eura Putz → "you\'re a putz"'],
  ['euraloozer', 'Eura Loozer → "you\'re a loser"'],
  ['eurasnott', 'Eura Snott → "you\'re a snot"'],

  // ── Ivor / Iona (I\'ve a …)
  ['ivorhardon', 'Ivor Hardon → "I\'ve a hard-on"'],
  ['ivorbigwun', 'Ivor Bigwun → "I\'ve a big one"'],
  ['ivorsorass', 'Ivor Sorass → "I\'ve a sore ass"'],

  // ── Misc anatomical
  ['tesstickles', 'Tess Tickles → "testicles"'],
  ['tesstikles', 'Tess Tikles → "testicles"'],
  ['weetoddid', 'Wee Todd Did → "I am retarded gag"'],
  ['willstroker', 'Willy Stroker → "willy stroker"'],
  ['willystroker', 'Willy Stroker'],
  ['willhung', 'Will Hung → "well hung"'],
  ['lonschlong', 'Long Schlong → "long schlong"'],
  ['hunglo', 'Hung Lo → "hung low"'],
  ['hungweilo', 'Hung Wei Lo → "hung way low"'],
  ['holeefuk', 'Ho Lee Fuk → "holy fuck"'],
  ['eatonbeaver', 'Eaton Beaver → "eatin\' beaver"'],
  ['eatiepussie', 'Eatie Pussie → "eat the pussy"'],
  ['peterlong', 'Peter Long → "peter (penis) long"'],
  ['peterfile', 'Peter File → "pedophile"'],
  ['peterpump', 'Peter Pump → "peter pump"'],
  ['dickhertz', 'Dick Hertz → "dick hurts"'],
  ['dickinurmouth', 'Dick Inurmouth → "dick in your mouth"'],
  ['dicklipps', 'Dick Lipps → "dick lips"'],
  ['dicklikker', 'Dick Likker → "dick licker"'],
  ['dickswallow', 'Dick Swallow → "dick swallow"'],
  ['richardcranium', 'Richard Cranium → "dickhead"'],
  ['frankfurter', 'Frank Furter → "frankfurter (penis slang)"'],
  ['franknbeans', 'Frank N. Beans → "franks and beans (genitals)"'],
  ['pearlnecklace', 'Pearl Necklace (sex slang)'],
  ['mistypussy', 'Misty Pussy → "moist genitals"'],
  ['sandycrotch', 'Sandy Crotch → "sandy crotch"'],
  ['sandyvagina', 'Sandy Vagina → "sandy vagina"'],
  ['lonschlong', 'Long Schlong → "long schlong"'],

  // ── Asian-phonetic prank-call gags (canon Bart Simpson)
  ['sumtingwong', 'Sum Ting Wong → "something wrong"'],
  ['witulo', 'Wi Tu Lo → "we too low"'],
  ['sumyunggai', 'Sum Yung Gai → "some young guy"'],
  ['bangdingow', 'Bang Ding Ow (crash sound gag)'],

  // ── Gag-name puns (less vulgar but still inappropriate for HALO)
  ['robingraves', 'Robin Graves → "robbing graves"'],
  ['robinbanks', 'Robin Banks → "robbing banks"'],
  ['barbdwyer', 'Barb Dwyer → "barbed wire"'],
  ['stupendous', 'Stu Pendous → "stupendous (gag)"'],
  ['hapehour', 'Hap E. Hour → "happy hour"'],
  ['noahlott', 'Noah Lott → "know a lot"'],
  ['olivenyou', 'Olive Yew → "I love you"'],
  ['polyesther', 'Polly Esther → "polyester"'],
  ['pollytickle', 'Polly Tickle → "political"'],
  ['terrybull', 'Terry Bull → "terrible"'],
  ['terrycloth', 'Terry Cloth → "terry cloth (gag)"'],
  ['sharonneedles', 'Sharon Needles → "sharing needles"'],
  ['ottomatic', 'Otto Matic → "automatic"'],
  ['ottomobile', 'Otto Mobile → "automobile"'],
  ['ottograf', 'Otto Graf → "autograph"'],
  ['ellavader', 'Ella Vader → "elevator / Darth Vader"'],
  ['ellaphant', 'Ella Phant → "elephant"'],
  ['waltermelon', 'Walter Melon → "watermelon"'],
  ['warrenpeace', 'Warren Peace → "War and Peace"'],
  ['willpower', 'Will Power → "willpower"'],
  ['rustybedsprings', 'Rusty Bedsprings (sex slang)'],
];

export const englishExactOnly = new Set([
  'ass', 'tit', 'fag', 'cum', 'jew',
]);
